spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecom_db


server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


jwt:
  secret: Bearer Aadhish1234@
  expiration: 86400000 # 1 day in milliseconds



